<home>
    <home-navigation></home-navigation>
    <home-content-hero></home-content-hero>
    <home-content-benefits></home-content-benefits>
    <home-slider-projects></home-slider-projects>
    <home-content-directions></home-content-directions>
    <home-content-users></home-content-users>
    <home-content-influence></home-content-influence>
    <home-slider-clients></home-slider-clients>
    <global-footer></global-footer>
</home>